### ISSUE TITLE
R version in jupyter kernel is incompatible with required R package Bioconductor

### ISSUE THREAD

**Issue by akafazov** [ALTERNATIVE-EU/platform-deployment#18]
Users need to install the R package **Bioconductor**. It requires R version 4.3.0. Jupyter ships with R version 4.0.4

References:
- https://bioconductor.org/install/

**Comment by vikig07** [comment]
@akafazov

I've updated the R version in the Jupyter image.

Users will need to add their previous package directory to R's paths, in order to use the packages they've already installed.

Commands (should be executed in R console):

(replace `yourLib` with the path to your package directory; by default that should have been `~/R/x86_64-pc-linux-gnu-library/4.0`)

To add the directory in paths list:
```
.libPaths( c( .libPaths(), "yourLib") )
```

To make the directory the main library for packages:
```
.libPaths( c( "yourLib" , .libPaths() ) )
```

**Comment by akafazov** [comment]
Thanks, I will inform the partners. Can you also update the jupyter documentation.

**Comment by vikig07** [comment]
Update docs - https://github.com/ALTERNATIVE-EU/alternative.github.io/commit/80f952a2af712e3164852a1564f04e67fa3860d8

**Comment by ignatov17** [comment]
Checked, R is upgraded to version 4.3.0 and the docs is updated
